name: Build Workflow

on:
  push:
#    branches: master

jobs:
  Build-And-Release:
    runs-on: windows-2019
    permissions: write-all
    steps:

      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12.7'
          architecture: 'x64'
      
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Build with pyinstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name=2G_bulk_trade_load ./app/2G_bulk_trade_load/2G_bulk_trade_load.py --distpath .
      
      # - name: Testing application status
      #   uses: GuillaumeFalourd/assert-command-line-output@v2
      #   with:
      #     command_line: 2G_bulk_trade_load.exe test
      #     contains: app run success
      #     expected_result: PASSED

      - name : Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: 2G_bulk_trade_load
          path: 2G_bulk_trade_load.exe

      - name : Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "V0.1.0"
          artifacts: "*.exe"
          prerelease: true
          allowUpdates: true